### ISSUE TITLE
Create Products model

### ISSUE THREAD

**Issue by maggieneterval** [maggieneterval/spell-store#1]
Create products model.

**Comment by nimadera** [comment]
Columns: product title, category, price, description, photo url, incantation, product id, inventory quantity, backorder restock date (optional - see separate card)

**Comment by nimadera** [comment]
The seven categories of spells are: charms, transfiguration, hexes, jinxes, curses, healing spells, and protective enchantments. 

We might be able to randomly generate product ids based on which category these fall under (assuming a spell can't be more than one thing). For example, all product ids are 5 digits. Charms are 1----, transfigurations are 2----, etc.
